# Generated by Django 4.0.4 on 2022-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_amountingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.AmountIngredient', to='api.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
